# Dealing with NumPy

In [1]:
import numpy as np
myarr= np.array([2,6,3,5])
myarr

array([2, 6, 3, 5])

this is one dimensional array

In [2]:
myarr.dtype

dtype('int32')

In [3]:
myarr.shape

In [4]:
myarr

array([2, 6, 3, 5])

In [5]:
myarr[2]

3

In [6]:
myarr[2]=45

In [7]:
myarr

array([ 2,  6, 45,  5])

In [8]:
myarr1= np.array([[2,6,3,5]])

this is 2 dimensional aaray

In [9]:
myarr1

array([[2, 6, 3, 5]])

In [10]:
myarr1[0,2]

3

In [11]:
myarr1[0,2]=22

In [12]:
myarr1

array([[ 2,  6, 22,  5]])

# Conversion from other Python structures

In [13]:
lstarray=np.array([[2,5,7,5,8],[7,9,7,5,1]])

In [14]:
lstarray

array([[2, 5, 7, 5, 8],
       [7, 9, 7, 5, 1]])

In [15]:
lstarray.dtype

dtype('int32')

In [16]:
lstarray.shape

(2, 5)

In [17]:
lstarray.size

10

In [18]:
np.array({2,6,5,4})

array({2, 4, 5, 6}, dtype=object)

**Array Creation from Dictonary**

In [19]:
lstarray1=np.array({2,7,8,9,57,5})

In [20]:
lstarray1

array({2, 5, 7, 8, 9, 57}, dtype=object)

In [21]:
lstarray1.size

1

In [22]:
lstarray.shape

(2, 5)

In [23]:
lstarray1.shape

()

# Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [24]:
zero=np.zeros((2,5))

In [25]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
rng=np.arange(15)

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
one=np.ones((2,5))

In [29]:
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
rng=np.arange(1,10,2)#last one is jumpindex=2

In [31]:
rng

array([1, 3, 5, 7, 9])

In [32]:
rng=np.arange(2)

In [33]:
rng

array([0, 1])

In [34]:
rng1=np.arange(101)

In [35]:
rng

array([0, 1])

In [36]:
rng1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
rng1=np.arange(1,101,2)

In [38]:
rng1

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [39]:
rng1=np.arange(99)

In [40]:
rng1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
np.arange(3,33)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

**linespace:- it will create a array with same line space it 1st and 2nd number will give the exact range of the number and the third one will give you how many number do you want to print**

In [42]:
lnsp=np.linspace(1,5,3)

In [43]:
lnsp

array([1., 3., 5.])

In [44]:
lnsp=np.linspace(1,5,10)

In [45]:
lnsp

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

**empty will give your desired empty array with random values of so you can change as per your need in row and column**

In [46]:
emp=np.empty((2,6))

In [47]:
emp

array([[6.38289234e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000, 1.10343781e-312, 3.69776220e-062],
       [5.89330534e-091, 1.46495774e-075, 6.55124554e-043,
        1.67501057e-076, 3.99910963e+252, 5.82471487e+257]])

**emptylike makes a copy of your old array and make it empty so that u can change as per your need**

In [48]:
emplike=np.empty_like(lnsp)

In [49]:
emplike

array([6.38289234e-312, 2.47032823e-322, 1.10343781e-312, 3.69776220e-062,
       5.89330534e-091, 1.46495774e-075, 6.55124554e-043, 1.67501057e-076,
       3.99910963e+252, 5.82471487e+257])

**np.identity will give you identity matrix of 0,1**

In [50]:
ide=np.identity(20)

In [51]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.

In [52]:
ide.shape

(20, 20)

**now there is 2 more method is present np.reshape and np.ravel**

**reshape will convert a 1d array into matrix form but u have to give the correct multiplication like 44(in 1d)=2x22(in 2d)**

In [53]:
arr=np.arange(44)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [55]:
arr=arr.reshape(44,1)

In [56]:
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31],
       [32],
       [33],
       [34],
       [35],
       [36],
       [37],
       [38],
       [39],
       [40],
       [41],
       [42],
       [43]])

**ravel will convert 2d into 1d**

In [57]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43])

In [58]:
arr.shape

(44, 1)

In [59]:
arr=arr.ravel()

In [60]:
arr.shape

(44,)

In [61]:
arr.shape

(44,)

**matrix operation /axis**

In [62]:
x=[[1,3,5],[5,8,2],[4,2,3]]

In [63]:
ar=np.array(x)

In [64]:
ar

array([[1, 3, 5],
       [5, 8, 2],
       [4, 2, 3]])

In [65]:
ar.sum(axis=0) #it will  add the column wise here there is 3 column (axis=0)

array([10, 13, 10])

In [66]:
ar.sum(axis=1)# it will add the row (axis=1)

array([ 9, 15,  9])

In [67]:
ar.T #to transpose a matrix capital T is used

array([[1, 5, 4],
       [3, 8, 2],
       [5, 2, 3]])

In [68]:
for i in ar:
    print(i)

[1 3 5]
[5 8 2]
[4 2 3]


In [69]:
for i in ar.flat:
    print(i)        #flat will give you a single single line

1
3
5
5
8
2
4
2
3


In [70]:
a=np.array([1,47,5,8,66])

In [71]:
a.argmax()#argmax will give u a index where the maximum value is present

4

In [72]:
a.argmin()#argmax will give u a index where the minimum value is present

0

In [73]:
a.argsort()#argsort will give you a sorted array but in index form means which index is an sorted manner

array([0, 2, 3, 1, 4], dtype=int64)

In [74]:
ar

array([[1, 3, 5],
       [5, 8, 2],
       [4, 2, 3]])

In [75]:
ar.argmax()

4

In [76]:
ar.argmin()

0

In [77]:
ar.argmax(axis=0)

array([1, 1, 0], dtype=int64)

In [78]:
ar.argmax(axis=1)

array([2, 1, 0], dtype=int64)

In [79]:
ar.argmin(axis=0)

array([0, 2, 1], dtype=int64)

In [80]:
ar.argmin(axis=1)

array([0, 2, 1], dtype=int64)

In [81]:
ar.argsort()

array([[0, 1, 2],
       [2, 0, 1],
       [1, 2, 0]], dtype=int64)

In [82]:
ar.reshape((9,1))

array([[1],
       [3],
       [5],
       [5],
       [8],
       [2],
       [4],
       [2],
       [3]])

In [83]:
ar.ravel()

array([1, 3, 5, 5, 8, 2, 4, 2, 3])

In [84]:
ar.reshape((3,3))

array([[1, 3, 5],
       [5, 8, 2],
       [4, 2, 3]])

# MATRIX OPERATION

In [85]:
mat1=np.arange(9)

In [86]:
mat1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
mat1=mat1.reshape((3,3))

In [88]:
mat2=np.arange(9,18)

In [89]:
mat2

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [90]:
mat2=mat2.reshape((3,3))

In [91]:
mat1+mat2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [92]:
mat1*mat2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [93]:
mat1-mat2

array([[-9, -9, -9],
       [-9, -9, -9],
       [-9, -9, -9]])

In [94]:
np.sqrt(mat1)#square of elements

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

**To check why numpy is used instead of simple python array**

In [ ]:
import sys

In [ ]:
py_s= [2,78,5,8]

In [ ]:
np_s= np.array(py_s)

In [ ]:
sys.getsizeof(1)*len(py_s)#simple python list is taking 112 bytes memory

In [ ]:
np_s.itemsize*np_s.size#numpy array is using 16 bytes of memory

**to know more about numpy methods and attributes:- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html**