In [1]:
import numpy as np

In [2]:
my_arr=np.arange(24)

In [3]:
my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
my_arr=my_arr.reshape(4,6)
my_arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

# Print 2nd and 3rd Column

In [14]:
my_arr[:,1:3]

array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]])

# Print Last 2 Columns

In [12]:
my_arr[:,-2:]

array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])

# Print 4th and 5th Column

In [8]:
my_arr[:, 3:5]

array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]])